volumes:
  postgres_db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /www/Mirror-Elf_data/postgres_data  # 指定外部的路径
  rabbitmq_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /www/Mirror-Elf_data/rabbitmq_data  # 指定外部的路径
      
services:
  mirror_elf:
    network_mode: host
    build: ./app
    container_name: mirror_elf
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://admin:mirrorelf@localhost/mirror
      - CELERY_BROKER_URL=amqp://admin:mirrorelf@localhost//
      - CELERY_RESULT_BACKEND=rpc://
      - WORKER_ACK_TIMEOUT=90
    volumes:
      - ./app:/app

  postgres:
    image: postgres:13
    container_name: postgres_db
    restart: on-failure
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mirrorelf
      POSTGRES_DB: mirror
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "max_connections=4096"]
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  garnet:
    image: 'ghcr.io/microsoft/garnet'
    container_name: garnet_service
    restart: on-failure
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    restart: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mirrorelf
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    command: sh -c "rabbitmq-server -rabbit max_connections 20480"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  flower:
      image: mher/flower
      container_name: flower
      restart: on-failure
      command: celery --broker=amqp://admin:mirrorelf@rabbitmq:5672// flower
      ports:
        - "5555:5555"
      depends_on:
        - rabbitmq
  
$WORKER_LOOP