services:
  mirror_elf:
    network_mode: host
    build: ./app
    container_name: mirror_elf
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://admin:mirrorelf@localhost/mirror
      - CELERY_BROKER_URL=amqp://admin:mirrorelf@localhost//
      - CELERY_RESULT_BACKEND=rpc://
      - WORKER_ACK_TIMEOUT=90
    volumes:
      - ./app:/app

  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mirrorelf
      POSTGRES_DB: mirror
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "max_connections=4096"]
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  garnet:
    image: 'ghcr.io/microsoft/garnet'
    container_name: garnet_service
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - garnet_data:/data

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mirrorelf
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    command: sh -c "rabbitmq-server -rabbit max_connections 20480"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  celery_worker_1:
    network_mode: host
    build: ./app
    container_name: celery_worker_1
    command: celery -A tasks worker -l info -P gevent -c 512 --prefetch-multiplier=1 -n celery_worker_1@%h
    environment:
      - CELERY_BROKER_URL=amqp://admin:mirrorelf@localhost//
      - CELERY_RESULT_BACKEND=rpc://
      - CELERY_RESULT_EXPIRES=300
      - CELERYD_PREFETCH_MULTIPLIER=1
    depends_on:
      - rabbitmq

  celery_worker_2:
    network_mode: host
    build: ./app
    container_name: celery_worker_2
    command: celery -A tasks worker -l info -P gevent -c 512 --prefetch-multiplier=1 -n celery_worker_2@%h
    environment:
      - CELERY_BROKER_URL=amqp://admin:mirrorelf@localhost//
      - CELERY_RESULT_BACKEND=rpc://
      - CELERY_RESULT_EXPIRES=300
      - CELERYD_PREFETCH_MULTIPLIER=1
    depends_on:
      - rabbitmq
    
  celery_worker_3:
    network_mode: host
    build: ./app
    container_name: celery_worker_3
    command: celery -A tasks worker -l info -P gevent -c 512 --prefetch-multiplier=1 -n celery_worker_3@%h
    environment:
      - CELERY_BROKER_URL=amqp://admin:mirrorelf@localhost//
      - CELERY_RESULT_BACKEND=rpc://
      - CELERY_RESULT_EXPIRES=300
      - CELERYD_PREFETCH_MULTIPLIER=1
    depends_on:
      - rabbitmq

  celery_worker_4:
    network_mode: host
    build: ./app
    container_name: celery_worker_4
    command: celery -A tasks worker -l info -P gevent -c 512 --prefetch-multiplier=1 -n celery_worker_4@%h
    environment:
      - CELERY_BROKER_URL=amqp://admin:mirrorelf@localhost//
      - CELERY_RESULT_BACKEND=rpc://
      - CELERY_RESULT_EXPIRES=300
      - CELERYD_PREFETCH_MULTIPLIER=1
    depends_on:
      - rabbitmq

  celery_worker_5:
    network_mode: host
    build: ./app
    container_name: celery_worker_5
    command: celery -A tasks worker -l info -P gevent -c 512 --prefetch-multiplier=1 -n celery_worker_5@%h
    environment:
      - CELERY_BROKER_URL=amqp://admin:mirrorelf@localhost//
      - CELERY_RESULT_BACKEND=rpc://
      - CELERY_RESULT_EXPIRES=300
      - CELERYD_PREFETCH_MULTIPLIER=1
    depends_on:
      - rabbitmq
    
  celery_worker_6:
    network_mode: host
    build: ./app
    container_name: celery_worker_6
    command: celery -A tasks worker -l info -P gevent -c 512 --prefetch-multiplier=1 -n celery_worker_6@%h
    environment:
      - CELERY_BROKER_URL=amqp://admin:mirrorelf@localhost//
      - CELERY_RESULT_BACKEND=rpc://
      - CELERY_RESULT_EXPIRES=300
      - CELERYD_PREFETCH_MULTIPLIER=1
    depends_on:
      - rabbitmq

  celery_worker_7:
    network_mode: host
    build: ./app
    container_name: celery_worker_7
    command: celery -A tasks worker -l info -P gevent -c 512 --prefetch-multiplier=1 -n celery_worker_7@%h
    environment:
      - CELERY_BROKER_URL=amqp://admin:mirrorelf@localhost//
      - CELERY_RESULT_BACKEND=rpc://
      - CELERY_RESULT_EXPIRES=300
      - CELERYD_PREFETCH_MULTIPLIER=1
    depends_on:
      - rabbitmq

  celery_worker_8:
    network_mode: host
    build: ./app
    container_name: celery_worker_8
    command: celery -A tasks worker -l info -P gevent -c 512 --prefetch-multiplier=1 -n celery_worker_8@%h
    environment:
      - CELERY_BROKER_URL=amqp://admin:mirrorelf@localhost//
      - CELERY_RESULT_BACKEND=rpc://
      - CELERY_RESULT_EXPIRES=300
      - CELERYD_PREFETCH_MULTIPLIER=1
    depends_on:
      - rabbitmq
    
  celery_worker_9:
    network_mode: host
    build: ./app
    container_name: celery_worker_9
    command: celery -A tasks worker -l info -P gevent -c 512 --prefetch-multiplier=1 -n celery_worker_9@%h
    environment:
      - CELERY_BROKER_URL=amqp://admin:mirrorelf@localhost//
      - CELERY_RESULT_BACKEND=rpc://
      - CELERY_RESULT_EXPIRES=300
      - CELERYD_PREFETCH_MULTIPLIER=1
    depends_on:
      - rabbitmq
      
  celery_worker_10:
    network_mode: host
    build: ./app
    container_name: celery_worker_10
    command: celery -A tasks worker -l info -P gevent -c 512 --prefetch-multiplier=1 -n celery_worker_10@%h
    environment:
      - CELERY_BROKER_URL=amqp://admin:mirrorelf@localhost//
      - CELERY_RESULT_BACKEND=rpc://
      - CELERY_RESULT_EXPIRES=300
      - CELERYD_PREFETCH_MULTIPLIER=1
    depends_on:
      - rabbitmq

  celery_worker_11:
    network_mode: host
    build: ./app
    container_name: celery_worker_11
    command: celery -A tasks worker -l info -P gevent -c 512 --prefetch-multiplier=1 -n celery_worker_11@%h
    environment:
      - CELERY_BROKER_URL=amqp://admin:mirrorelf@localhost//
      - CELERY_RESULT_BACKEND=rpc://
      - CELERY_RESULT_EXPIRES=300
      - CELERYD_PREFETCH_MULTIPLIER=1
    depends_on:
      - rabbitmq
    
  celery_worker_12:
    network_mode: host
    build: ./app
    container_name: celery_worker_12
    command: celery -A tasks worker -l info -P gevent -c 512 --prefetch-multiplier=1 -n celery_worker_12@%h
    environment:
      - CELERY_BROKER_URL=amqp://admin:mirrorelf@localhost//
      - CELERY_RESULT_BACKEND=rpc://
      - CELERY_RESULT_EXPIRES=300
      - CELERYD_PREFETCH_MULTIPLIER=1
    depends_on:
      - rabbitmq

  celery_worker_13:
    network_mode: host
    build: ./app
    container_name: celery_worker_13
    command: celery -A tasks worker -l info -P gevent -c 512 --prefetch-multiplier=1 -n celery_worker_13@%h
    environment:
      - CELERY_BROKER_URL=amqp://admin:mirrorelf@localhost//
      - CELERY_RESULT_BACKEND=rpc://
      - CELERY_RESULT_EXPIRES=300
      - CELERYD_PREFETCH_MULTIPLIER=1
    depends_on:
      - rabbitmq

  celery_worker_14:
    network_mode: host
    build: ./app
    container_name: celery_worker_14
    command: celery -A tasks worker -l info -P gevent -c 512 --prefetch-multiplier=1 -n celery_worker_14@%h
    environment:
      - CELERY_BROKER_URL=amqp://admin:mirrorelf@localhost//
      - CELERY_RESULT_BACKEND=rpc://
      - CELERY_RESULT_EXPIRES=300
      - CELERYD_PREFETCH_MULTIPLIER=1
    depends_on:
      - rabbitmq
    
  celery_worker_15:
    network_mode: host
    build: ./app
    container_name: celery_worker_15
    command: celery -A tasks worker -l info -P gevent -c 512 --prefetch-multiplier=1 -n celery_worker_15@%h
    environment:
      - CELERY_BROKER_URL=amqp://admin:mirrorelf@localhost//
      - CELERY_RESULT_BACKEND=rpc://
      - CELERY_RESULT_EXPIRES=300
      - CELERYD_PREFETCH_MULTIPLIER=1
    depends_on:
      - rabbitmq
      
  celery_worker_16:
    network_mode: host
    build: ./app
    container_name: celery_worker_16
    command: celery -A tasks worker -l info -P gevent -c 512 --prefetch-multiplier=1 -n celery_worker_16@%h
    environment:
      - CELERY_BROKER_URL=amqp://admin:mirrorelf@localhost//
      - CELERY_RESULT_BACKEND=rpc://
      - CELERY_RESULT_EXPIRES=300
      - CELERYD_PREFETCH_MULTIPLIER=1
    depends_on:
      - rabbitmq

  flower:
    image: mher/flower
    container_name: flower
    command: celery --broker=amqp://admin:mirrorelf@rabbitmq:5672// flower
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq

volumes:
  postgres_db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /www/Mirror-Elf/data/postgres_data  # 指定外部的路径
  garnet_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /www/Mirror-Elf/data/garnet_data  # 指定外部的路径
  rabbitmq_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /www/Mirror-Elf/data/rabbitmq_data  # 指定外部的路径