【网站信息】:
  授权码: ''
  登录账号: 'admin'
  登录密码: 'admin'
  程序名称: 'web1 - Mirror-Elf by TG@seo898'

【网站设置】:
  自动建站: True # 关闭时: 不自动生成首页网站配置 www.domain.com_zh_www.target.com_zh.yml
  语言: 'zh' # zh:中文 | zh-Hant:繁体中文 | en:英文 | pt:葡萄牙文
  缓存静态文件: '.ico' # 静态文件保存到target缓存中，其它静态将通过流式代理返回 '.css|.js|.png|.jpg|.ico|.svg|.gif|.jpeg'
  首页更新时间: 1 # 单位：天 如果想永不更新首页，填写99999即可
  链接映射: True # 开启后，repalce.yml中的链接映射生效

【目录功能】: # 默认目录模板路径为：site/template
  模板模式: '404' # 关闭:不调用模板 | 404:目标站404时返回模板 | 泛目录:所有内页调用模板，缓存页面| 蜘蛛池:所有内页调用模板，不缓存页面
  TDK格式: '{base_url}{网站地图专用随机内链}' # 开启后，目录内页会引用配置文件中的TDK
  地图链接数量: 500 # 指定sitemap1.txt  sitemap123.xml 中随机生成的链接数量
  地图链接格式: '{base_url}{网站地图专用随机内链}' # 此处引用标签 详情至 config/标签.yml

【SEO功能】:
  图片翻转: True # ‘静态文件远程调用’需关闭，且‘缓存文件名’中需加入'.png', '.jpg', '.ico','.svg', '.gif', '.jpeg' 图片翻转方可生效
  随机meta&link: False
  随机class属性: False
  html压缩: False
  js加密混淆: True # “静态文件远程调用”需关闭，缓存js文件时生效
  css加密混淆: True # “静态文件远程调用”需关闭，缓存css文件时生效

【访问策略】:
  非绑定域名来路: True
  IP与非域名来路: True
  UA黑名单: 'Scrapy|Curl|HttpClient|UniversalFeedParser|lightDeckReports Bot|heritrix|Java|Bytespider|YandexBot|FlightDeckReports|Indy Library|BOT/0.1|DigExt|Feedly|Swiftbot|oBot|Python-urllib|CrawlDaddy|YYSpider|JikeSpider|ZmEu|MJ12bot|WebZIP|Apache-HttpAsyncClient|HttpClient|WinHttp|jaunty|Alexa Toolbar|LinkpadBot|Microsoft URL Control|node-superagent|Ezooms|Jullo|SemrushBot|FetchURL|AhrefsBot|EasouSpider|java/|CoolpadWebkit|Linguee Bot|ApacheBench|AskTbFXTV|FeedDemon'
  IP黑名单: '888.888.888.888|88.88.88.88|10.240.2.131'

【广告策略】:
  广告URL: "http://www.baidu.com"
  搜索来路跳广告: False
  普通用户跳广告: False

【全局代码插入】: # 一般用于插入网站统计和JS广告 过滤IP填写本地IP可过滤掉插入的广告
  过滤IP: '192.168.1.1|168.0.0.1'
  head头部: ''
  head尾部: '<script src="/_/static/js/ad.js" type="text/javascript"></script>'
  body头部: ''
  body尾部: '<script src="/_/static/js/tongji.js" type="text/javascript"></script>'

【蜘蛛策略】:
  谷歌蜘蛛: True
  百度蜘蛛: True
  必应蜘蛛: True